import Foundation

/// Набор системных логов для фазы вывода в терминал
struct LogData {
    static let systemLogs: [String] = [
        "[*] Cort1so1 Exploit Engine v1.0.5 (iOS 26.0 - arm64e)",
        "[*] Проверка архитектуры: Apple Silicon Neural Subsystem",
        "[*] Определение базового адреса mach_kernel: 0xfffffff007004000",
        "[*] Вычисление KASLR Slide: 0x000000001bc24000",
        "[*] Чтение карты физической памяти: 0xffffffe000000000 - 0xffffffe3ffffffff",
        "[+] Найдено смещение allproc: 0xfffffff00938b120",
        "[+] Найдено смещение kernel_task: 0xfffffff009395018",
        "[+] Найдено смещение realhost: 0xfffffff0093005a0",
        "[*] Запуск примитива kread64/kwrite64 через PhysPuppet...",
        "[+] Примитив произвольного чтения/записи ядра активирован.",
        "[*] Поиск структуры proc_t текущего процесса (PID: 4082)...",
        "[+] proc_t обнаружен по адресу: 0xffffffe28a34b210",
        "[*] Чтение поля ucred: 0xffffffe19402e180",
        "[+] Подмена credentials: UID 501 -> UID 0 (root).",
        "[+] Флаги cr_svgid сброшены. Повышение привилегий завершено.",
        "[*] Запуск фазы отключения песочницы (Mach Sandbox Escape)...",
        "[+] Песочница отключена для текущего task_t.",
        "[*] Анализ системы защиты AMFI (Apple Mobile File Integrity)...",
        "[*] Патчинг функции amfi_execve_hook: 0xfffffff00812e940 -> NOP",
        "[+] Флаги cs_enforcement успешно деактивированы в kernel memory.",
        "[*] Анализ CoreTrust: обход валидации подписи Mach-O...",
        "[+] Добавлен динамический trustcache в список ядра (0xffffffe21109a000).",
        "[*] Проверка статуса PPL/SPTM (Page Protection Layer)...",
        "[+] Страницы L2 PTE успешно разблокированы для записи.",
        "[*] Монтирование корневой файловой системы APFS snapshot...",
        "[+] Точка монтирования: /private/preboot/cort1so1_rootfs (rw).",
        "[*] Проверка целостности базового окружения Bootstrap...",
        "[*] Развертывание Procursus Bootstrap (zstd archive)...",
        "[*] Извлечение /usr/bin/dpkg [OK]",
        "[*] Извлечение /usr/bin/apt [OK]",
        "[*] Извлечение /usr/bin/sh [OK]",
        "[*] Извлечение /usr/lib/libsubstrate.dylib [OK]",
        "[*] Извлечение /Applications/Sileo.app [OK]",
        "[*] Извлечение /Applications/Zebra.app [OK]",
        "[*] Настройка прав доступа и битов setuid для системных утилит...",
        "[*] Запуск фонового демона cort1so1_daemon (jbd26)...",
        "[+] Демон активен на локальном сокете /var/run/cort1so1.sock.",
        "[*] Инъекция хуков в launchd (PID: 1)...",
        "[+] Твик-инжектор успешно перехватил libsystem_trace.dylib.",
        "[*] Очистка системных кэшей dyld_shared_cache и TLB...",
        "[+] Среда джейлбрейка Cort1so1 полностью подготовлена!",
        "[*] Синхронизация файловых дескрипторов (sync)...",
        "[*] Инициализация модуля перезапуска SpringBoard...",
        "[*] Запуск NeoSpringView..."
    ]
}
